apiVersion: template.openshift.io/v1
kind: Template
labels:
  app: aro-clf-law
  template: aro-clf-law
message: |-
  The following service(s) have been created in your project: ${NAME}.
metadata:
  annotations:
    description: A template to deploy cluster log forwarding to an Azure Log Analytics workspace
    openshift.io/display-name: ARO cluster log forwarder
    openshift.io/long-description: This template defines resources needed to forward logs from ARO to an Azure Log Analytics Workspace
  name: aro-cluster-log-forward
objects:

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app.kubernetes.io/name: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - port: 24224
      protocol: TCP
      targetPort: 24224
    selector:
      app.kubernetes.io/name: ${NAME}


- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      app.kubernetes.io/name: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}


- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: ${NAME}
    labels:
      app.kubernetes.io/name: ${NAME}
  rules:
  - apiGroups:
    - ""
    resources:
    - namespaces
    - pods
    verbs:
    - get
    - watch
    - list


- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: ${NAME}
    labels:
      app.kubernetes.io/name: ${NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: ${NAME}
  subjects:
  - kind: ServiceAccount
    name: ${NAME}
    namespace: ${NAMESPACE}


  
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/name: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  data:
    fluent-bit.conf: |
      [SERVICE]
          Flush         1
          Log_Level     info
          Daemon        off
          Parsers_File  parsers.conf
          HTTP_Server   On
          HTTP_Listen   0.0.0.0
          HTTP_Port     2020
      @INCLUDE input.conf
      @INCLUDE output.conf
    output.conf: |
      [OUTPUT]
          Name            azure
          Match           *.*
          Customer_ID     ${WorkspaceId}
          Shared_Key      ${SharedKey}
          Log_Type        openshift
    input.conf: |
      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
          Buffer_Chunk_Size 1M
          Buffer_Max_Size   10M


- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    labels:
      app.kubernetes.io/name: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: ${NAME}
    template:
      metadata:
        labels:
          app.kubernetes.io/name: ${NAME}
      spec:
        containers:
        - env:
          - name: WorkspaceId
            valueFrom:
              secretKeyRef:
                key: WorkspaceId
                name: ${NAME}
          - name: SharedKey
            valueFrom:
              secretKeyRef:
                key: SharedKey
                name: ${NAME}
          - name: LogName
            value: logapp
          image: fluent/fluent-bit:${FLUENT_BIT_VERSION}
          imagePullPolicy: IfNotPresent
          name: fluent-bit
          ports:
          - containerPort: 2020
            protocol: TCP
          - containerPort: 24224
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /fluent-bit/etc/
            name: fluent-bit-etc
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: ${NAME}
        serviceAccountName: ${NAME}
        terminationGracePeriodSeconds: 10
        volumes:
        - configMap:
            defaultMode: 420
            name: ${NAME}
          name: fluent-bit-etc
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
      type: RollingUpdate


- apiVersion: logging.openshift.io/v1
  kind: ClusterLogging
  metadata:
    labels:
      app.kubernetes.io/name: ${NAME}
    name: instance
    namespace: ${LOGGING_NAMESPACE}
  spec:
    collection:
      type: fluentd
    forwarder:
      managementState: Managed


- apiVersion: logging.openshift.io/v1
  kind: ClusterLogForwarder
  metadata:
    labels:
      app.kubernetes.io/name: ${NAME}
    name: instance
    namespace: ${LOGGING_NAMESPACE}
  spec:
    outputs:
    - name: fluentbit
      type: fluentdForward
      url: tcp://${NAME}.${NAMESPACE}:24224
    pipelines:
    - inputRefs:
      - infrastructure
      - application
      - audit
      name: forward-to-fluentbit
      outputRefs:
      - fluentbit

parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
  value: aro-clf-law

- description: The OpenShift Namespace where the Daemonset resides
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: cluster-log-forwarder

- description: The OpenShift Logging Namespace where the CRDs resides
  displayName: LoggingNamespace
  name: LOGGING_NAMESPACE
  required: true
  value: openshift-logging
  
- description: The version of fluent-bit container
  displayName: Fluent Bit Version
  name: FLUENT_BIT_VERSION
  required: true
  value: latest