# Red Hat Elasticsearch Operator Group
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-operators-redhat-
  namespace: openshift-operators-redhat
spec:
  upgradeStrategy: Default