# Red Hat OpenShift Logging Operator Group
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  generateName: openshift-logging-
  namespace: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
  upgradeStrategy: Default