name: Cleanup ALL Resources
on: [workflow_dispatch]

jobs: 
  cleanup_hub:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: hub cleanup
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.HUB_RG }}
        template: ./modules/resource_group_cleanup.bicep
        deploymentMode: Complete
        deploymentName: hub-resource-cleanup-github

  cleanup_spoke:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: spoke cleanup
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.SPOKE_RG }}
        template: ./modules/resource_group_cleanup.bicep
        deploymentMode: Complete
        deploymentName: spoke-resource-cleanup-github

  cleanup_resources:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: spoke cleanup
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        subscriptionId: ${{ vars.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ vars.SERVICES_RG }}
        template: ./modules/resource_group_cleanup.bicep
        deploymentMode: Complete
        deploymentName: services-resource-cleanup-github